/**
 * Adobe Edge: symbol definitions
 */
(function($, Edge, compId){
//images folder
var im='images/';

var fonts = {};


var resources = [
];
var symbols = {
"stage": {
   version: "2.0.1",
   minimumCompatibleVersion: "2.0.0",
   build: "2.0.1.268",
   baseState: "Base State",
   initialState: "Base State",
   gpuAccelerate: false,
   resizeInstances: false,
   content: {
         dom: [
         {
            id:'_2012102321505821',
            type:'image',
            rect:['0%','-38.5%','100%','138.5%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"2012102321505821.jpg",'0px','0px']
         },
         {
            id:'gp13-3',
            type:'image',
            rect:['100%','7%','69.1%','68.9%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"gp13-3.jpg",'0px','0px'],
            boxShadow:["",3,3,3,0,"rgba(0,0,0,0.65)"]
         },
         {
            id:'gp13-4',
            display:'none',
            type:'image',
            rect:['100%','31.1%','69.1%','68.9%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"gp13-4.png",'0px','0px'],
            boxShadow:["",3,3,3,0,"rgba(0,0,0,0.65)"]
         },
         {
            id:'gp13-5',
            display:'none',
            type:'image',
            rect:['100%','7.6%','69.1%','68.9%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"gp13-5.png",'0px','0px'],
            boxShadow:["",3,3,3,0,"rgba(0,0,0,0.65)"]
         },
         {
            id:'gp13-6',
            display:'none',
            type:'image',
            rect:['100%','26.3%','69.1%','68.9%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"gp13-6.jpg",'0px','0px'],
            boxShadow:["",0,0,15,0,"rgba(0,0,0,0.65)"]
         },
         {
            id:'TXT-Title1',
            display:'none',
            type:'text',
            rect:['0px','25%','100%','33.9%','auto','auto'],
            text:"雅诗的 2013年8月 感谢祭<br>（半年版大感谢祭）",
            align:"center",
            font:['Arial, Helvetica, sans-serif',[400,"%"],"rgba(0,0,0,1)","normal","none","normal"],
            textShadow:["rgba(241,167,255,1.00)",0,0,15]
         },
         {
            id:'TXT-Title2',
            display:'none',
            type:'text',
            rect:['31.4%','72.5%','37.1%','19.3%','auto','auto'],
            text:"8月，我来到姬家的第6个月<br>以后继续请多指教~❤<br><br>那么本月的右上Top35都是谁呢？",
            align:"center",
            font:['Arial, Helvetica, sans-serif',[200,"%"],"rgba(0,0,0,1)","normal","none","normal"],
            textShadow:["rgba(239,255,0,0.75)",3,3,3]
         },
         {
            id:'gp13-7',
            display:'none',
            type:'image',
            rect:['100%','7.3%','69.1%','68.9%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"gp13-7.png",'0px','0px'],
            boxShadow:["",0,0,15,0,"rgba(0,0,0,0.65)"]
         },
         {
            id:'T-XiaoQiu',
            display:'none',
            type:'text',
            rect:['9.6%','66.4%','34.4%','14.8%','auto','auto'],
            cursor:['help'],
            text:"Top35<br>+神北小毬（whoA's）",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1.00)","normal","none","normal"],
            textShadow:["rgba(247,255,0,1.00)",0,0,15]
         },
         {
            id:'U-XiaoQiu',
            display:'none',
            type:'image',
            rect:['50%','4.1%','50%','95.9%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-XiaoQiu.png",'0px','0px']
         },
         {
            id:'T-jyuntang',
            display:'none',
            type:'text',
            rect:['2.9%','9.1%','27.7%','14.8%','auto','auto'],
            cursor:['help'],
            text:"Top34<br>+Jyun-Tang Zeng",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,3,15]
         },
         {
            id:'U-jyuntang',
            display:'none',
            type:'image',
            rect:['19.9%','14.8%','31.5%','51.8%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-jyuntang.png",'0px','0px']
         },
         {
            id:'T-WuYue',
            display:'none',
            type:'text',
            rect:['20.6%','64.3%','20.7%','22.3%','auto','auto'],
            cursor:['help'],
            text:"Top33<br>+五月栞",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-WuYue',
            display:'none',
            type:'image',
            rect:['37.8%','3.9%','54%','95.6%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-WuYue.png",'0px','0px']
         },
         {
            id:'T-XuShu',
            display:'none',
            type:'text',
            rect:['62.8%','60.7%','33.1%','22.3%','auto','auto'],
            cursor:['help'],
            text:"Top32<br>+Miya Lyly (茜樹)",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-XuShu',
            display:'none',
            type:'image',
            rect:['0%','3.9%','54.1%','96%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-XuShu.png",'0px','0px']
         },
         {
            id:'T-JiaDaHao',
            display:'none',
            type:'text',
            rect:['5.9%','100%','43.1%','14.8%','auto','auto'],
            cursor:['help'],
            text:"Top31<br>+Harry Cheng<br>   (加大号的猫)",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-JiaDaHao',
            display:'none',
            type:'image',
            rect:['37.1%','-150.9%','62.9%','154.1%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-JiaDaHao.png",'0px','0px']
         },
         {
            id:'T-TonyZhao',
            display:'none',
            type:'text',
            rect:['70.6%','58.2%','18.8%','14.8%','auto','auto'],
            cursor:['help'],
            text:"Top30<br>+Tony Zhao",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-TonyZhao',
            display:'none',
            type:'image',
            rect:['0%','3.7%','54.5%','96.3%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-TonyZhao.png",'0px','0px']
         },
         {
            id:'T-XsummerXia',
            display:'none',
            type:'text',
            rect:['100%','62.8%','39.2%','18.5%','auto','auto'],
            cursor:['help'],
            text:"Top29<br>+Xsummer Xia (叉夏)",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,3,15]
         },
         {
            id:'U-XsummerXia',
            display:'none',
            type:'image',
            rect:['-44.4%','4.5%','43.9%','95.6%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-XsummerXia.png",'0px','0px']
         },
         {
            id:'T-YookkeiLau',
            display:'none',
            type:'text',
            rect:['-35.4%','62.5%','35.4%','21.5%','auto','auto'],
            cursor:['help'],
            text:"Top28<br>+Yookkei Lau",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,3,15]
         },
         {
            id:'U-YookkeiLau',
            display:'none',
            type:'image',
            rect:['100%','3.9%','72.4%','96.1%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-YookkeiLau.png",'0px','0px']
         },
         {
            id:'T-KeKai',
            display:'none',
            type:'text',
            rect:['72.9%','-16%','19.5%','19.3%','auto','auto'],
            cursor:['help'],
            text:"Top27<br>+ke kai",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,3,15]
         },
         {
            id:'U-KeKai',
            display:'none',
            type:'image',
            rect:['9.9%','100%','39.2%','95.2%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-KeKai.png",'0px','0px']
         },
         {
            id:'T-slb1',
            display:'none',
            type:'text',
            rect:['100%','61.5%','30.7%','20.7%','auto','auto'],
            cursor:['help'],
            text:"Top26<br>+神楽坂アイス",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-slb1',
            display:'none',
            type:'image',
            rect:['-64.9%','3.9%','64.9%','96.4%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-slb1.png",'0px','0px']
         },
         {
            id:'T-Sora',
            display:'none',
            type:'text',
            rect:['-39%','58.3%','42.4%','22.5%','auto','auto'],
            cursor:['help'],
            text:"Top25<br>+Sora Kasugano (骚啦)",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-Sora',
            display:'none',
            type:'image',
            rect:['-53.4%','3.9%','54.4%','96.1%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-Sora.png",'0px','0px']
         },
         {
            id:'T-fzs',
            display:'none',
            type:'text',
            rect:['59.6%','-13.9%','24.6%','22.1%','auto','auto'],
            cursor:['help'],
            text:"Top24<br>+風之水",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-fzs',
            display:'none',
            type:'image',
            rect:['-24.6%','5.6%','24.6%','94.4%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-fzs.png",'0px','0px']
         },
         {
            id:'T-MountainChen',
            display:'none',
            type:'text',
            rect:['100%','55.2%','27.1%','22.3%','auto','auto'],
            cursor:['help'],
            text:"Top23<br>+Mountain Chen<br>  (小盆友的三周目)",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,3,15]
         },
         {
            id:'U-MountainChen',
            display:'none',
            type:'image',
            rect:['-54.6%','3.9%','54.6%','96.4%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-MountainChen.png",'0px','0px']
         },
         {
            id:'T-ARIAAOI',
            display:'none',
            type:'text',
            rect:['-19.7%','63.8%','22.3%','19.3%','auto','auto'],
            cursor:['help'],
            text:"Top22<br>+ARIA AOI",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1.00)","normal","none",""],
            textShadow:["rgba(255,255,0,1.00)",0,3,15]
         },
         {
            id:'U-ARIAAOI',
            display:'none',
            type:'image',
            rect:['100%','3.7%','41%','96.2%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-ARIAAOI.png",'0px','0px']
         },
         {
            id:'T-kirikakuMori',
            display:'none',
            type:'text',
            rect:['100%','63.4%','30.5%','20.2%','auto','auto'],
            cursor:['help'],
            text:"Top21<br>+kirikaku mori",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-kirikakuMori',
            display:'none',
            type:'image',
            rect:['-25.1%','3.9%','25.2%','95.9%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-kirikakuMori.png",'0px','0px']
         },
         {
            id:'T-johnnyJo',
            display:'none',
            type:'text',
            rect:['-17.9%','60.2%','24.3%','21.9%','auto','auto'],
            cursor:['help'],
            text:"Top20<br>+johnny jo",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-johnnyJo',
            display:'none',
            type:'image',
            rect:['100%','4.2%','53.9%','95.8%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-johnnyJo.png",'0px','0px']
         },
         {
            id:'T-DaisukeMineko',
            display:'none',
            type:'text',
            rect:['100%','59.6%','41%','14.8%','auto','auto'],
            cursor:['help'],
            text:"Top19<br>+Daisuke Mineko (米喵子)",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,3,15]
         },
         {
            id:'U-DaisukeMineko',
            display:'none',
            type:'image',
            rect:['-51.2%','3.9%','51.2%','96.1%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-DaisukeMineko.png",'0px','0px']
         },
         {
            id:'T-HuiChu',
            display:'none',
            type:'text',
            rect:['17.4%','64.1%','17.4%','20.8%','auto','auto'],
            text:"Top18<br>+灰触",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,0,15]
         },
         {
            id:'U-HuiChu',
            display:'none',
            type:'image',
            rect:['53.2%','3.9%','46.8%','248.1%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-HuiChu.png",'0px','0px']
         },
         {
            id:'T-TianShiHui',
            display:'none',
            type:'text',
            rect:['-13.1%','62.2%','18.7%','19.3%','auto','auto'],
            cursor:['help'],
            text:"Top17<br>+天使恵",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[300,"%"],"rgba(255,255,255,1)","normal","none","normal"],
            textShadow:["rgba(255,255,0,1.00)",0,3,15]
         },
         {
            id:'U-TianShiHui',
            display:'none',
            type:'image',
            rect:['100%','3.9%','51.4%','96.2%','auto','auto'],
            fill:["rgba(0,0,0,0)",im+"U-TianShiHui.png",'0px','0px']
         },
         {
            id:'TitleBar',
            type:'rect',
            rect:['0px','0px','100%','30px','auto','auto'],
            fill:["rgba(0,0,0,1.00)"],
            stroke:[0,"rgba(0,0,0,1)","none"]
         },
         {
            id:'TXT-Pyashi',
            type:'text',
            rect:['13px','7px','81px','18px','auto','auto'],
            cursor:['pointer'],
            text:"+神樂坂雅詩",
            align:"left",
            font:['Arial, Helvetica, sans-serif',[80,"%"],"rgba(255,255,255,1.00)","normal","none","normal"]
         }],
         symbolInstances: [

         ]
      },
   states: {
      "Base State": {
         "${_gp13-7}": [
            ["style", "top", '7.55%'],
            ["subproperty", "boxShadow.blur", '15px'],
            ["subproperty", "boxShadow.offsetH", '0px'],
            ["style", "display", 'none'],
            ["subproperty", "boxShadow.offsetV", '0px'],
            ["style", "left", '100%'],
            ["subproperty", "boxShadow.color", 'rgba(0,0,0,0.65)']
         ],
         "${_U-WuYue}": [
            ["style", "top", '5.21%'],
            ["style", "height", '95.57%'],
            ["style", "display", 'none'],
            ["style", "left", '-53.98%'],
            ["style", "width", '53.98%']
         ],
         "${_T-WuYue}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "cursor", 'help'],
            ["style", "width", '20.74%'],
            ["style", "top", '66.41%'],
            ["style", "display", 'none'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "height", '22.27%'],
            ["style", "left", '100.44%']
         ],
         "${_T-KeKai}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '3px'],
            ["style", "left", '66.62%'],
            ["style", "width", '19.49%'],
            ["style", "top", '-16.01%'],
            ["style", "height", '19.27%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "cursor", 'help'],
            ["style", "display", 'none']
         ],
         "${_U-Sora}": [
            ["style", "top", '3.26%'],
            ["style", "display", 'none'],
            ["style", "height", '96.08%'],
            ["style", "left", '-53.39%'],
            ["style", "width", '54.35%']
         ],
         "${_U-KeKai}": [
            ["style", "top", '100%'],
            ["style", "display", 'none'],
            ["style", "height", '95.18%'],
            ["style", "left", '10.29%'],
            ["style", "width", '39.23%']
         ],
         "${_T-MountainChen}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '3px'],
            ["style", "left", '100%'],
            ["style", "width", '32.06%'],
            ["style", "top", '55.2%'],
            ["style", "height", '27.74%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "cursor", 'help'],
            ["style", "display", 'none']
         ],
         "${_T-YookkeiLau}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '3px'],
            ["style", "left", '100%'],
            ["style", "width", '35.38%'],
            ["style", "top", '58.34%'],
            ["style", "height", '21.48%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "display", 'none'],
            ["style", "cursor", 'help']
         ],
         "${_U-YookkeiLau}": [
            ["style", "top", '3.91%'],
            ["style", "height", '96.09%'],
            ["style", "display", 'none'],
            ["style", "left", '-72.41%'],
            ["style", "width", '72.41%']
         ],
         "${_U-ARIAAOI}": [
            ["style", "top", '3.91%'],
            ["style", "height", '96.2%'],
            ["style", "display", 'none'],
            ["style", "left", '100%'],
            ["style", "width", '41.03%']
         ],
         "${_gp13-4}": [
            ["style", "top", '26.17%'],
            ["subproperty", "boxShadow.blur", '15px'],
            ["style", "left", '100%'],
            ["style", "display", 'none'],
            ["subproperty", "boxShadow.offsetV", '3px'],
            ["subproperty", "boxShadow.offsetH", '0px'],
            ["subproperty", "boxShadow.color", 'rgba(0,0,0,0.65)']
         ],
         "${_U-MountainChen}": [
            ["style", "top", '3.91%'],
            ["style", "display", 'none'],
            ["style", "height", '96.35%'],
            ["style", "left", '-54.56%'],
            ["style", "width", '54.56%']
         ],
         "${_T-TianShiHui}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '3px'],
            ["style", "left", '-13.08%'],
            ["style", "width", '18.68%'],
            ["style", "top", '62.24%'],
            ["style", "height", '19.27%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "display", 'none'],
            ["style", "cursor", 'help']
         ],
         "${_T-ARIAAOI}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["style", "display", 'none'],
            ["color", "color", 'rgba(255,255,255,1.00)'],
            ["subproperty", "textShadow.offsetV", '3px'],
            ["style", "cursor", 'help'],
            ["style", "font-size", '300%'],
            ["style", "top", '63.8%'],
            ["style", "width", '22.28%'],
            ["style", "left", '-19.71%'],
            ["style", "text-indent", '0%'],
            ["style", "height", '19.27%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "word-spacing", '0em'],
            ["style", "letter-spacing", '0em']
         ],
         "${_U-TonyZhao}": [
            ["style", "top", '100%'],
            ["style", "height", '96.28%'],
            ["style", "display", 'none'],
            ["style", "left", '0%'],
            ["style", "width", '54.49%']
         ],
         "${_U-TianShiHui}": [
            ["style", "top", '3.91%'],
            ["style", "height", '96.17%'],
            ["style", "display", 'none'],
            ["style", "left", '100%'],
            ["style", "width", '51.41%']
         ],
         "${_U-jyuntang}": [
            ["style", "top", '3.91%'],
            ["style", "display", 'none'],
            ["style", "height", '96.14%'],
            ["style", "left", '3.97%'],
            ["style", "width", '58.39%']
         ],
         "${_T-JiaDaHao}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "cursor", 'help'],
            ["style", "width", '43.09%'],
            ["style", "top", '100%'],
            ["style", "display", 'none'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "height", '24.21%'],
            ["style", "left", '7.49%']
         ],
         "${_T-Sora}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '-38.97%'],
            ["style", "width", '42.43%'],
            ["style", "top", '60.66%'],
            ["style", "height", '22.52%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "cursor", 'help'],
            ["style", "display", 'none']
         ],
         "${_T-XuShu}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '100%'],
            ["style", "width", '33.09%'],
            ["style", "top", '62.5%'],
            ["style", "height", '22.27%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "cursor", 'help'],
            ["style", "display", 'none']
         ],
         "${_T-XsummerXia}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '3px'],
            ["style", "cursor", 'help'],
            ["style", "width", '39.2%'],
            ["style", "top", '-18.49%'],
            ["style", "height", '18.49%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "display", 'none'],
            ["style", "left", '5.14%']
         ],
         "${_U-XiaoQiu}": [
            ["style", "top", '3.26%'],
            ["style", "display", 'none'],
            ["style", "height", '95.89%'],
            ["style", "left", '-50%'],
            ["style", "width", '50%']
         ],
         "${_T-XiaoQiu}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["color", "color", 'rgba(255,255,255,1.00)'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '100%'],
            ["style", "font-size", '300%'],
            ["style", "top", '66.66%'],
            ["style", "text-align", 'left'],
            ["style", "display", 'none'],
            ["style", "height", '14.84%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "width", '34.42%'],
            ["style", "cursor", 'help']
         ],
         "${_U-slb1}": [
            ["style", "top", '3.91%'],
            ["style", "display", 'none'],
            ["style", "height", '96.35%'],
            ["style", "left", '-64.93%'],
            ["style", "width", '64.94%']
         ],
         "${__2012102321505821}": [
            ["style", "top", '-38.54%'],
            ["style", "left", '0%'],
            ["style", "height", '138.54%']
         ],
         "${_T-HuiChu}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '17.36%'],
            ["style", "width", '17.36%'],
            ["style", "top", '-16.92%'],
            ["style", "height", '20.83%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "display", 'none']
         ],
         "${_U-HuiChu}": [
            ["style", "top", '100%'],
            ["style", "height", '248.12%'],
            ["style", "display", 'none'],
            ["style", "left", '53.16%'],
            ["style", "width", '46.84%']
         ],
         "${_U-XuShu}": [
            ["style", "top", '3.91%'],
            ["style", "height", '95.57%'],
            ["style", "display", 'none'],
            ["style", "left", '-54.05%'],
            ["style", "width", '53.82%']
         ],
         "${_U-DaisukeMineko}": [
            ["style", "top", '3.91%'],
            ["style", "height", '96.05%'],
            ["style", "display", 'none'],
            ["style", "left", '-51.18%'],
            ["style", "width", '51.18%']
         ],
         "${_T-fzs}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '57.5%'],
            ["style", "width", '24.56%'],
            ["style", "top", '-13.93%'],
            ["style", "height", '22.14%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "cursor", 'help'],
            ["style", "display", 'none']
         ],
         "${_U-JiaDaHao}": [
            ["style", "top", '-150.91%'],
            ["style", "height", '154.1%'],
            ["style", "display", 'none'],
            ["style", "left", '37.13%'],
            ["style", "width", '62.87%']
         ],
         "${_U-fzs}": [
            ["style", "top", '3.65%'],
            ["style", "display", 'none'],
            ["style", "height", '97.24%'],
            ["style", "left", '-24.56%'],
            ["style", "width", '25.3%']
         ],
         "${_TitleBar}": [
            ["style", "height", '30px'],
            ["color", "background-color", 'rgba(0,0,0,1.00)'],
            ["style", "left", '0px'],
            ["style", "width", '100%']
         ],
         "${_T-jyuntang}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '3px'],
            ["style", "left", '2.94%'],
            ["style", "width", '27.73%'],
            ["style", "top", '66.67%'],
            ["style", "display", 'none'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "cursor", 'help'],
            ["style", "height", '14.84%']
         ],
         "${_U-XsummerXia}": [
            ["style", "top", '4.45%'],
            ["style", "height", '95.55%'],
            ["style", "display", 'none'],
            ["style", "left", '100%'],
            ["style", "width", '43.9%']
         ],
         "${_U-johnnyJo}": [
            ["style", "top", '3.91%'],
            ["style", "height", '95.84%'],
            ["style", "display", 'none'],
            ["style", "left", '100%'],
            ["style", "width", '53.91%']
         ],
         "${_T-DaisukeMineko}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '3px'],
            ["style", "left", '100%'],
            ["style", "width", '49.12%'],
            ["style", "top", '59.63%'],
            ["style", "height", '22.13%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "display", 'none'],
            ["style", "cursor", 'help']
         ],
         "${_T-TonyZhao}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '70.65%'],
            ["style", "width", '18.83%'],
            ["style", "top", '-14.84%'],
            ["style", "height", '14.84%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "cursor", 'help'],
            ["style", "display", 'none']
         ],
         "${_T-johnnyJo}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '-17.95%'],
            ["style", "width", '24.34%'],
            ["style", "top", '60.15%'],
            ["style", "height", '21.88%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "display", 'none'],
            ["style", "cursor", 'help']
         ],
         "${_T-kirikakuMori}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '100%'],
            ["style", "width", '30.45%'],
            ["style", "top", '63.41%'],
            ["style", "height", '20.18%'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "display", 'none'],
            ["style", "cursor", 'help']
         ],
         "${_T-slb1}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '100%'],
            ["style", "width", '30.68%'],
            ["style", "top", '61.2%'],
            ["style", "cursor", 'help'],
            ["style", "display", 'none'],
            ["subproperty", "textShadow.color", 'rgba(255,255,0,1.00)'],
            ["style", "text-decoration", 'none'],
            ["style", "height", '20.7%']
         ],
         "${_U-kirikakuMori}": [
            ["style", "top", '3.91%'],
            ["style", "height", '95.89%'],
            ["style", "display", 'none'],
            ["style", "left", '-25.15%'],
            ["style", "width", '25.15%']
         ],
         "${_gp13-5}": [
            ["style", "top", '7.8%'],
            ["subproperty", "boxShadow.blur", '15px'],
            ["style", "left", '100%'],
            ["style", "display", 'none'],
            ["subproperty", "boxShadow.offsetV", '0px'],
            ["subproperty", "boxShadow.offsetH", '0px'],
            ["subproperty", "boxShadow.color", 'rgba(0,0,0,0.65)']
         ],
         "${_TXT-Pyashi}": [
            ["style", "letter-spacing", '0em'],
            ["color", "color", 'rgba(255,255,255,1.00)'],
            ["style", "font-weight", 'normal'],
            ["style", "left", '13px'],
            ["style", "font-size", '80%'],
            ["style", "top", '7px'],
            ["style", "text-indent", '0%'],
            ["style", "height", '18px'],
            ["style", "cursor", 'pointer'],
            ["style", "word-spacing", '0em'],
            ["style", "width", '81px']
         ],
         "${_gp13-6}": [
            ["style", "top", '26.82%'],
            ["subproperty", "boxShadow.blur", '15px'],
            ["subproperty", "boxShadow.offsetH", '0px'],
            ["style", "display", 'none'],
            ["subproperty", "boxShadow.offsetV", '0px'],
            ["style", "left", '100%'],
            ["subproperty", "boxShadow.color", 'rgba(0,0,0,0.65)']
         ],
         "${_T-XiaoQiuCopy}": [
            ["style", "top", '66.66%'],
            ["style", "font-size", '300%'],
            ["style", "left", '100%'],
            ["style", "display", 'none'],
            ["style", "height", '14.84%'],
            ["color", "color", 'rgba(255,255,255,1.00)'],
            ["style", "cursor", 'pointer'],
            ["style", "width", '34.42%']
         ],
         "${_Stage}": [
            ["color", "background-color", 'rgba(187,231,255,1.00)'],
            ["style", "min-width", '720px'],
            ["style", "overflow", 'hidden'],
            ["style", "height", '100%'],
            ["style", "width", '100%']
         ],
         "${_TXT-Title1}": [
            ["subproperty", "textShadow.blur", '15px'],
            ["subproperty", "textShadow.offsetH", '0px'],
            ["subproperty", "textShadow.offsetV", '0px'],
            ["style", "left", '0px'],
            ["style", "width", '100%'],
            ["style", "top", '25%'],
            ["style", "font-size", '400%'],
            ["style", "height", '33.85%'],
            ["subproperty", "textShadow.color", 'rgba(241,167,255,1.00)'],
            ["style", "font-style", 'normal'],
            ["style", "display", 'none']
         ],
         "${_gp13-3}": [
            ["style", "top", '6.77%'],
            ["subproperty", "boxShadow.blur", '15px'],
            ["style", "left", '100%'],
            ["style", "display", 'block'],
            ["subproperty", "boxShadow.offsetV", '0px'],
            ["subproperty", "boxShadow.offsetH", '3px'],
            ["subproperty", "boxShadow.color", 'rgba(0,0,0,0.65)']
         ],
         "${_TXT-Title2}": [
            ["subproperty", "textShadow.blur", '3px'],
            ["subproperty", "textShadow.offsetH", '3px'],
            ["subproperty", "textShadow.offsetV", '3px'],
            ["style", "left", '-0.13%'],
            ["style", "font-size", '200%'],
            ["style", "top", '72.53%'],
            ["style", "width", '100%'],
            ["style", "height", '19.27%'],
            ["subproperty", "textShadow.color", 'rgba(239,255,0,0.75)'],
            ["style", "display", 'none'],
            ["style", "opacity", '0']
         ]
      }
   },
   timelines: {
      "Default Timeline": {
         fromState: "Base State",
         toState: "",
         duration: 47000,
         autoPlay: true,
         timeline: [
            { id: "eid628", tween: [ "style", "${_T-TianShiHui}", "left", '59.42%', { fromValue: '-13.08%'}], position: 45000, duration: 500 },
            { id: "eid631", tween: [ "style", "${_T-TianShiHui}", "left", '67.95%', { fromValue: '59.42%'}], position: 45500, duration: 1000 },
            { id: "eid632", tween: [ "style", "${_T-TianShiHui}", "left", '100%', { fromValue: '67.95%'}], position: 46500, duration: 500 },
            { id: "eid417", tween: [ "style", "${_U-KeKai}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid392", tween: [ "style", "${_U-KeKai}", "display", 'block', { fromValue: 'none'}], position: 30000, duration: 0 },
            { id: "eid410", tween: [ "style", "${_U-KeKai}", "display", 'none', { fromValue: 'block'}], position: 32000, duration: 0 },
            { id: "eid612", tween: [ "style", "${_T-HuiChu}", "top", '56.52%', { fromValue: '-16.92%'}], position: 43500, duration: 500 },
            { id: "eid615", tween: [ "style", "${_T-HuiChu}", "top", '66.68%', { fromValue: '56.52%'}], position: 44000, duration: 1000 },
            { id: "eid618", tween: [ "style", "${_T-HuiChu}", "top", '-16.92%', { fromValue: '66.68%'}], position: 45000, duration: 500 },
            { id: "eid621", tween: [ "style", "${_U-HuiChu}", "left", '100%', { fromValue: '53.16%'}], position: 45000, duration: 500 },
            { id: "eid355", tween: [ "style", "${_T-XsummerXia}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid325", tween: [ "style", "${_T-XsummerXia}", "display", 'block', { fromValue: 'none'}], position: 26750, duration: 0 },
            { id: "eid353", tween: [ "style", "${_T-XsummerXia}", "display", 'none', { fromValue: 'block'}], position: 29000, duration: 0 },
            { id: "eid294", tween: [ "style", "${_T-JiaDaHao}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid272", tween: [ "style", "${_T-JiaDaHao}", "display", 'block', { fromValue: 'none'}], position: 23500, duration: 0 },
            { id: "eid288", tween: [ "style", "${_T-JiaDaHao}", "display", 'none', { fromValue: 'block'}], position: 25500, duration: 0 },
            { id: "eid218", tween: [ "style", "${_U-WuYue}", "left", '37.21%', { fromValue: '-53.98%'}], position: 20500, duration: 500 },
            { id: "eid229", tween: [ "style", "${_U-WuYue}", "left", '43.83%', { fromValue: '37.21%'}], position: 21000, duration: 1000 },
            { id: "eid238", tween: [ "style", "${_U-WuYue}", "left", '100%', { fromValue: '43.83%'}], position: 22000, duration: 500 },
            { id: "eid49", tween: [ "style", "${_gp13-3}", "left", '-69.12%', { fromValue: '100%'}], position: 0, duration: 4000 },
            { id: "eid401", tween: [ "style", "${_T-KeKai}", "top", '59%', { fromValue: '-16.01%'}], position: 30000, duration: 500 },
            { id: "eid406", tween: [ "style", "${_T-KeKai}", "top", '67.85%', { fromValue: '59%'}], position: 30500, duration: 1000 },
            { id: "eid414", tween: [ "style", "${_T-KeKai}", "top", '100%', { fromValue: '67.85%'}], position: 31500, duration: 500 },
            { id: "eid293", tween: [ "style", "${_U-JiaDaHao}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid271", tween: [ "style", "${_U-JiaDaHao}", "display", 'block', { fromValue: 'none'}], position: 23500, duration: 0 },
            { id: "eid286", tween: [ "style", "${_U-JiaDaHao}", "display", 'none', { fromValue: 'block'}], position: 25500, duration: 0 },
            { id: "eid306", tween: [ "style", "${_U-TonyZhao}", "top", '3.72%', { fromValue: '100%'}], position: 25000, duration: 500 },
            { id: "eid318", tween: [ "style", "${_U-TonyZhao}", "top", '100%', { fromValue: '3.72%'}], position: 26750, duration: 500 },
            { id: "eid623", tween: [ "style", "${_T-HuiChu}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid606", tween: [ "style", "${_T-HuiChu}", "display", 'block', { fromValue: 'none'}], position: 43500, duration: 0 },
            { id: "eid619", tween: [ "style", "${_T-HuiChu}", "display", 'none', { fromValue: 'block'}], position: 45500, duration: 0 },
            { id: "eid276", tween: [ "style", "${_T-JiaDaHao}", "top", '61.71%', { fromValue: '100%'}], position: 23500, duration: 500 },
            { id: "eid283", tween: [ "style", "${_T-JiaDaHao}", "top", '54.94%', { fromValue: '61.71%'}], position: 24000, duration: 1000 },
            { id: "eid290", tween: [ "style", "${_T-JiaDaHao}", "top", '-24.21%', { fromValue: '54.94%'}], position: 25000, duration: 500 },
            { id: "eid335", tween: [ "style", "${_T-XsummerXia}", "top", '64.58%', { fromValue: '-18.49%'}], position: 26750, duration: 500 },
            { id: "eid341", tween: [ "style", "${_T-XsummerXia}", "top", '69.01%', { fromValue: '64.58%'}], position: 27250, duration: 1250 },
            { id: "eid348", tween: [ "style", "${_T-XsummerXia}", "top", '100%', { fromValue: '69.01%'}], position: 28500, duration: 500 },
            { id: "eid636", tween: [ "style", "${_U-TianShiHui}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid624", tween: [ "style", "${_U-TianShiHui}", "display", 'block', { fromValue: 'none'}], position: 45000, duration: 0 },
            { id: "eid634", tween: [ "style", "${_U-TianShiHui}", "display", 'none', { fromValue: 'block'}], position: 47000, duration: 0 },
            { id: "eid205", tween: [ "style", "${_U-jyuntang}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid177", tween: [ "style", "${_U-jyuntang}", "display", 'block', { fromValue: 'none'}], position: 19000, duration: 0 },
            { id: "eid203", tween: [ "style", "${_U-jyuntang}", "display", 'none', { fromValue: 'block'}], position: 21000, duration: 0 },
            { id: "eid81", tween: [ "style", "${_gp13-5}", "left", '-69.12%', { fromValue: '100%'}], position: 4000, duration: 4000 },
            { id: "eid322", tween: [ "style", "${_T-TonyZhao}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid303", tween: [ "style", "${_T-TonyZhao}", "display", 'block', { fromValue: 'none'}], position: 25000, duration: 0 },
            { id: "eid316", tween: [ "style", "${_T-TonyZhao}", "display", 'none', { fromValue: 'block'}], position: 27250, duration: 0 },
            { id: "eid374", tween: [ "style", "${_U-YookkeiLau}", "left", '27.59%', { fromValue: '-72.41%'}], position: 28500, duration: 500 },
            { id: "eid380", tween: [ "style", "${_U-YookkeiLau}", "left", '35.53%', { fromValue: '27.59%'}], position: 29000, duration: 1000 },
            { id: "eid389", tween: [ "style", "${_U-YookkeiLau}", "left", '100%', { fromValue: '35.53%'}], position: 30000, duration: 500 },
            { id: "eid63", tween: [ "style", "${_gp13-4}", "left", '-69.12%', { fromValue: '100%'}], position: 2000, duration: 4000 },
            { id: "eid521", tween: [ "style", "${_U-MountainChen}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid502", tween: [ "style", "${_U-MountainChen}", "display", 'block', { fromValue: 'none'}], position: 36000, duration: 0 },
            { id: "eid513", tween: [ "style", "${_U-MountainChen}", "display", 'none', { fromValue: 'block'}], position: 38000, duration: 0 },
            { id: "eid99", tween: [ "style", "${_gp13-7}", "left", '-69.12%', { fromValue: '100%'}], position: 8000, duration: 4000 },
            { id: "eid550", tween: [ "style", "${_T-kirikakuMori}", "left", '18.23%', { fromValue: '100%'}], position: 39000, duration: 500 },
            { id: "eid554", tween: [ "style", "${_T-kirikakuMori}", "left", '13.23%', { fromValue: '18.23%'}], position: 39500, duration: 1000 },
            { id: "eid560", tween: [ "style", "${_T-kirikakuMori}", "left", '-30.45%', { fromValue: '13.23%'}], position: 40500, duration: 500 },
            { id: "eid331", tween: [ "style", "${_U-XsummerXia}", "left", '56.1%', { fromValue: '100%'}], position: 26750, duration: 500 },
            { id: "eid351", tween: [ "style", "${_U-XsummerXia}", "left", '100%', { fromValue: '56.1%'}], position: 28500, duration: 500 },
            { id: "eid112", tween: [ "style", "${_TXT-Title2}", "top", '72.53%', { fromValue: '72.53%'}], position: 12500, duration: 0 },
            { id: "eid118", tween: [ "style", "${_TXT-Title2}", "top", '-19.27%', { fromValue: '72.53%'}], position: 16000, duration: 1000 },
            { id: "eid109", tween: [ "style", "${__2012102321505821}", "top", '3.26%', { fromValue: '-38.54%'}], position: 0, duration: 12000 },
            { id: "eid122", tween: [ "style", "${__2012102321505821}", "top", '-38.54%', { fromValue: '3.26%'}], position: 16000, duration: 1500 },
            { id: "eid470", tween: [ "style", "${_U-fzs}", "left", '-1.17%', { fromValue: '-24.56%'}], position: 34500, duration: 500 },
            { id: "eid488", tween: [ "style", "${_U-fzs}", "left", '-0.05%', { fromValue: '-1.17%'}], position: 35000, duration: 1000 },
            { id: "eid493", tween: [ "style", "${_U-fzs}", "left", '-25.3%', { fromValue: '-0.05%'}], position: 36000, duration: 500 },
            { id: "eid522", tween: [ "style", "${_T-MountainChen}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid503", tween: [ "style", "${_T-MountainChen}", "display", 'block', { fromValue: 'none'}], position: 36000, duration: 0 },
            { id: "eid515", tween: [ "style", "${_T-MountainChen}", "display", 'none', { fromValue: 'block'}], position: 38000, duration: 0 },
            { id: "eid277", tween: [ "style", "${_U-JiaDaHao}", "top", '-54.1%', { fromValue: '-150.91%'}], position: 23500, duration: 500 },
            { id: "eid285", tween: [ "style", "${_U-JiaDaHao}", "top", '20.58%', { fromValue: '-54.1%'}], position: 24000, duration: 1000 },
            { id: "eid292", tween: [ "style", "${_U-JiaDaHao}", "top", '100%', { fromValue: '20.58%'}], position: 25000, duration: 500 },
            { id: "eid462", tween: [ "style", "${_U-Sora}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid441", tween: [ "style", "${_U-Sora}", "display", 'block', { fromValue: 'none'}], position: 33000, duration: 0 },
            { id: "eid454", tween: [ "style", "${_U-Sora}", "display", 'none', { fromValue: 'block'}], position: 35000, duration: 0 },
            { id: "eid149", tween: [ "style", "${_U-XiaoQiu}", "left", '45.29%', { fromValue: '-50%'}], position: 17500, duration: 500 },
            { id: "eid160", tween: [ "style", "${_U-XiaoQiu}", "left", '50%', { fromValue: '45.29%'}], position: 18000, duration: 1000 },
            { id: "eid164", tween: [ "style", "${_U-XiaoQiu}", "left", '100%', { fromValue: '50%'}], position: 19000, duration: 500 },
            { id: "eid223", tween: [ "style", "${_T-WuYue}", "left", '20.59%', { fromValue: '100.44%'}], position: 20500, duration: 500 },
            { id: "eid230", tween: [ "style", "${_T-WuYue}", "left", '12.5%', { fromValue: '20.59%'}], position: 21000, duration: 1000 },
            { id: "eid236", tween: [ "style", "${_T-WuYue}", "left", '-20.74%', { fromValue: '12.5%'}], position: 22000, duration: 500 },
            { id: "eid372", tween: [ "style", "${_T-YookkeiLau}", "left", '14.62%', { fromValue: '100%'}], position: 28500, duration: 500 },
            { id: "eid381", tween: [ "style", "${_T-YookkeiLau}", "left", '6.91%', { fromValue: '14.62%'}], position: 29000, duration: 1000 },
            { id: "eid387", tween: [ "style", "${_T-YookkeiLau}", "left", '-28.47%', { fromValue: '6.91%'}], position: 30000, duration: 500 },
            { id: "eid637", tween: [ "style", "${_T-TianShiHui}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid626", tween: [ "style", "${_T-TianShiHui}", "display", 'block', { fromValue: 'none'}], position: 45000, duration: 0 },
            { id: "eid635", tween: [ "style", "${_T-TianShiHui}", "display", 'none', { fromValue: 'block'}], position: 47000, duration: 0 },
            { id: "eid267", tween: [ "style", "${_U-XuShu}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid246", tween: [ "style", "${_U-XuShu}", "display", 'block', { fromValue: 'none'}], position: 22000, duration: 0 },
            { id: "eid263", tween: [ "style", "${_U-XuShu}", "display", 'none', { fromValue: 'block'}], position: 24000, duration: 0 },
            { id: "eid629", tween: [ "style", "${_U-TianShiHui}", "left", '11.76%', { fromValue: '100%'}], position: 45000, duration: 500 },
            { id: "eid630", tween: [ "style", "${_U-TianShiHui}", "left", '7.5%', { fromValue: '11.76%'}], position: 45500, duration: 1000 },
            { id: "eid633", tween: [ "style", "${_U-TianShiHui}", "left", '-51.41%', { fromValue: '7.5%'}], position: 46500, duration: 500 },
            { id: "eid255", tween: [ "style", "${_T-XuShu}", "left", '62.79%', { fromValue: '100%'}], position: 22000, duration: 500 },
            { id: "eid259", tween: [ "style", "${_T-XuShu}", "left", '65.29%', { fromValue: '62.79%'}], position: 22500, duration: 1000 },
            { id: "eid264", tween: [ "style", "${_T-XuShu}", "left", '100%', { fromValue: '65.29%'}], position: 23500, duration: 500 },
            { id: "eid613", tween: [ "style", "${_U-HuiChu}", "top", '3.26%', { fromValue: '100%'}], position: 43500, duration: 500 },
            { id: "eid614", tween: [ "style", "${_U-HuiChu}", "top", '-148.12%', { fromValue: '3.26%'}], position: 44000, duration: 1000 },
            { id: "eid622", tween: [ "style", "${_U-HuiChu}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid607", tween: [ "style", "${_U-HuiChu}", "display", 'block', { fromValue: 'none'}], position: 43500, duration: 0 },
            { id: "eid617", tween: [ "style", "${_U-HuiChu}", "display", 'none', { fromValue: 'block'}], position: 45500, duration: 0 },
            { id: "eid439", tween: [ "style", "${_U-slb1}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid420", tween: [ "style", "${_U-slb1}", "display", 'block', { fromValue: 'none'}], position: 31500, duration: 0 },
            { id: "eid437", tween: [ "style", "${_U-slb1}", "display", 'none', { fromValue: 'block'}], position: 33500, duration: 0 },
            { id: "eid531", tween: [ "style", "${_T-ARIAAOI}", "left", '63.53%', { fromValue: '-19.71%'}], position: 37500, duration: 500 },
            { id: "eid535", tween: [ "style", "${_T-ARIAAOI}", "left", '66.91%', { fromValue: '63.53%'}], position: 38000, duration: 1000 },
            { id: "eid540", tween: [ "style", "${_T-ARIAAOI}", "left", '100%', { fromValue: '66.91%'}], position: 39000, duration: 500 },
            { id: "eid183", tween: [ "style", "${_U-jyuntang}", "left", '10.14%', { fromValue: '3.97%'}], position: 19000, duration: 500 },
            { id: "eid196", tween: [ "style", "${_U-jyuntang}", "left", '3.97%', { fromValue: '10.14%'}], position: 19500, duration: 1000 },
            { id: "eid199", tween: [ "style", "${_U-jyuntang}", "left", '-58.39%', { fromValue: '3.97%'}], position: 20500, duration: 500 },
            { id: "eid354", tween: [ "style", "${_U-XsummerXia}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid323", tween: [ "style", "${_U-XsummerXia}", "display", 'block', { fromValue: 'none'}], position: 26750, duration: 0 },
            { id: "eid352", tween: [ "style", "${_U-XsummerXia}", "display", 'none', { fromValue: 'block'}], position: 29000, duration: 0 },
            { id: "eid500", tween: [ "style", "${_T-fzs}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid467", tween: [ "style", "${_T-fzs}", "display", 'block', { fromValue: 'none'}], position: 34500, duration: 0 },
            { id: "eid498", tween: [ "style", "${_T-fzs}", "display", 'none', { fromValue: 'block'}], position: 36500, duration: 0 },
            { id: "eid104", tween: [ "style", "${_gp13-7}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid97", tween: [ "style", "${_gp13-7}", "display", 'block', { fromValue: 'none'}], position: 8000, duration: 0 },
            { id: "eid103", tween: [ "style", "${_gp13-7}", "display", 'none', { fromValue: 'block'}], position: 12000, duration: 0 },
            { id: "eid475", tween: [ "style", "${_T-fzs}", "top", '58.99%', { fromValue: '-13.93%'}], position: 34500, duration: 500 },
            { id: "eid484", tween: [ "style", "${_T-fzs}", "top", '67.32%', { fromValue: '58.99%'}], position: 35000, duration: 1000 },
            { id: "eid495", tween: [ "style", "${_T-fzs}", "top", '100%', { fromValue: '67.32%'}], position: 36000, duration: 500 },
            { id: "eid562", tween: [ "style", "${_U-kirikakuMori}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid545", tween: [ "style", "${_U-kirikakuMori}", "display", 'block', { fromValue: 'none'}], position: 39000, duration: 0 },
            { id: "eid556", tween: [ "style", "${_U-kirikakuMori}", "display", 'none', { fromValue: 'block'}], position: 41000, duration: 0 },
            { id: "eid119", tween: [ "style", "${_TXT-Title2}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid110", tween: [ "style", "${_TXT-Title2}", "display", 'block', { fromValue: 'none'}], position: 12500, duration: 0 },
            { id: "eid117", tween: [ "style", "${_TXT-Title2}", "display", 'none', { fromValue: 'block'}], position: 17000, duration: 0 },
            { id: "eid570", tween: [ "style", "${_T-johnnyJo}", "left", '17.64%', { fromValue: '-17.95%'}], position: 40500, duration: 500 },
            { id: "eid575", tween: [ "style", "${_T-johnnyJo}", "left", '21.17%', { fromValue: '17.64%'}], position: 41000, duration: 1000 },
            { id: "eid579", tween: [ "style", "${_T-johnnyJo}", "left", '-18.68%', { fromValue: '21.17%'}], position: 42000, duration: 500 },
            { id: "eid154", tween: [ "style", "${_T-XiaoQiu}", "left", '11.62%', { fromValue: '100%'}], position: 17500, duration: 500 },
            { id: "eid162", tween: [ "style", "${_T-XiaoQiu}", "left", '7.35%', { fromValue: '11.62%'}], position: 18000, duration: 1000 },
            { id: "eid167", tween: [ "style", "${_T-XiaoQiu}", "left", '-34.42%', { fromValue: '7.35%'}], position: 19000, duration: 500 },
            { id: "eid448", tween: [ "style", "${_U-Sora}", "left", '-2.65%', { fromValue: '-53.39%'}], position: 33000, duration: 500 },
            { id: "eid453", tween: [ "style", "${_U-Sora}", "left", '0%', { fromValue: '-2.65%'}], position: 33500, duration: 1000 },
            { id: "eid460", tween: [ "style", "${_U-Sora}", "left", '-54.35%', { fromValue: '0%'}], position: 34500, duration: 500 },
            { id: "eid445", tween: [ "style", "${_T-Sora}", "left", '49.41%', { fromValue: '-38.97%'}], position: 33000, duration: 500 },
            { id: "eid452", tween: [ "style", "${_T-Sora}", "left", '57.57%', { fromValue: '49.41%'}], position: 33500, duration: 1000 },
            { id: "eid458", tween: [ "style", "${_T-Sora}", "left", '100%', { fromValue: '57.57%'}], position: 34500, duration: 500 },
            { id: "eid427", tween: [ "style", "${_U-slb1}", "left", '-2.13%', { fromValue: '-64.93%'}], position: 31500, duration: 500 },
            { id: "eid430", tween: [ "style", "${_U-slb1}", "left", '0%', { fromValue: '-2.13%'}], position: 32000, duration: 1000 },
            { id: "eid433", tween: [ "style", "${_U-slb1}", "left", '-64.94%', { fromValue: '0%'}], position: 33000, duration: 500 },
            { id: "eid390", tween: [ "style", "${_U-YookkeiLau}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid356", tween: [ "style", "${_U-YookkeiLau}", "display", 'block', { fromValue: 'none'}], position: 28500, duration: 0 },
            { id: "eid383", tween: [ "style", "${_U-YookkeiLau}", "display", 'none', { fromValue: 'block'}], position: 30500, duration: 0 },
            { id: "eid604", tween: [ "style", "${_T-DaisukeMineko}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid588", tween: [ "style", "${_T-DaisukeMineko}", "display", 'block', { fromValue: 'none'}], position: 42000, duration: 0 },
            { id: "eid602", tween: [ "style", "${_T-DaisukeMineko}", "display", 'none', { fromValue: 'block'}], position: 44000, duration: 0 },
            { id: "eid590", tween: [ "style", "${_T-DaisukeMineko}", "left", '11.76%', { fromValue: '100%'}], position: 42000, duration: 500 },
            { id: "eid594", tween: [ "style", "${_T-DaisukeMineko}", "left", '7.79%', { fromValue: '11.76%'}], position: 42500, duration: 1000 },
            { id: "eid598", tween: [ "style", "${_T-DaisukeMineko}", "left", '100%', { fromValue: '7.79%'}], position: 43500, duration: 500 },
            { id: "eid125", tween: [ "style", "${_TXT-Title1}", "top", '100%', { fromValue: '25%'}], position: 16500, duration: 1000 },
            { id: "eid563", tween: [ "style", "${_T-kirikakuMori}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid547", tween: [ "style", "${_T-kirikakuMori}", "display", 'block', { fromValue: 'none'}], position: 39000, duration: 0 },
            { id: "eid558", tween: [ "style", "${_T-kirikakuMori}", "display", 'none', { fromValue: 'block'}], position: 41000, duration: 0 },
            { id: "eid603", tween: [ "style", "${_U-DaisukeMineko}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid586", tween: [ "style", "${_U-DaisukeMineko}", "display", 'block', { fromValue: 'none'}], position: 42000, duration: 0 },
            { id: "eid601", tween: [ "style", "${_U-DaisukeMineko}", "display", 'none', { fromValue: 'block'}], position: 44000, duration: 0 },
            { id: "eid589", tween: [ "style", "${_U-DaisukeMineko}", "left", '45.44%', { fromValue: '-51.18%'}], position: 42000, duration: 500 },
            { id: "eid593", tween: [ "style", "${_U-DaisukeMineko}", "left", '48.82%', { fromValue: '45.44%'}], position: 42500, duration: 1000 },
            { id: "eid597", tween: [ "style", "${_U-DaisukeMineko}", "left", '-51.18%', { fromValue: '48.82%'}], position: 43500, duration: 500 },
            { id: "eid463", tween: [ "style", "${_T-Sora}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid444", tween: [ "style", "${_T-Sora}", "display", 'block', { fromValue: 'none'}], position: 33000, duration: 0 },
            { id: "eid456", tween: [ "style", "${_T-Sora}", "display", 'none', { fromValue: 'block'}], position: 35000, duration: 0 },
            { id: "eid321", tween: [ "style", "${_U-TonyZhao}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid302", tween: [ "style", "${_U-TonyZhao}", "display", 'block', { fromValue: 'none'}], position: 25000, duration: 0 },
            { id: "eid314", tween: [ "style", "${_U-TonyZhao}", "display", 'none', { fromValue: 'block'}], position: 27250, duration: 0 },
            { id: "eid84", tween: [ "style", "${_gp13-5}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid72", tween: [ "style", "${_gp13-5}", "display", 'block', { fromValue: 'none'}], position: 4000, duration: 0 },
            { id: "eid79", tween: [ "style", "${_gp13-5}", "display", 'none', { fromValue: 'block'}], position: 8000, duration: 0 },
            { id: "eid584", tween: [ "style", "${_T-johnnyJo}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid567", tween: [ "style", "${_T-johnnyJo}", "display", 'block', { fromValue: 'none'}], position: 40500, duration: 0 },
            { id: "eid582", tween: [ "style", "${_T-johnnyJo}", "display", 'none', { fromValue: 'block'}], position: 42500, duration: 0 },
            { id: "eid157", tween: [ "style", "${_U-XiaoQiu}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid141", tween: [ "style", "${_U-XiaoQiu}", "display", 'block', { fromValue: 'none'}], position: 17500, duration: 0 },
            { id: "eid201", tween: [ "style", "${_U-XiaoQiu}", "display", 'none', { fromValue: 'block'}], position: 19500, duration: 0 },
            { id: "eid250", tween: [ "style", "${_U-XuShu}", "left", '0%', { fromValue: '-54.05%'}], position: 22000, duration: 500 },
            { id: "eid266", tween: [ "style", "${_U-XuShu}", "left", '-53.82%', { fromValue: '0%'}], position: 23500, duration: 500 },
            { id: "eid583", tween: [ "style", "${_U-johnnyJo}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid565", tween: [ "style", "${_U-johnnyJo}", "display", 'block', { fromValue: 'none'}], position: 40500, duration: 0 },
            { id: "eid581", tween: [ "style", "${_U-johnnyJo}", "display", 'none', { fromValue: 'block'}], position: 42500, duration: 0 },
            { id: "eid571", tween: [ "style", "${_U-johnnyJo}", "left", '48.38%', { fromValue: '100%'}], position: 40500, duration: 500 },
            { id: "eid576", tween: [ "style", "${_U-johnnyJo}", "left", '46.09%', { fromValue: '48.38%'}], position: 41000, duration: 1000 },
            { id: "eid580", tween: [ "style", "${_U-johnnyJo}", "left", '100%', { fromValue: '46.09%'}], position: 42000, duration: 500 },
            { id: "eid551", tween: [ "style", "${_U-kirikakuMori}", "left", '56.91%', { fromValue: '-25.15%'}], position: 39000, duration: 500 },
            { id: "eid555", tween: [ "style", "${_U-kirikakuMori}", "left", '61.32%', { fromValue: '56.91%'}], position: 39500, duration: 1000 },
            { id: "eid561", tween: [ "style", "${_U-kirikakuMori}", "left", '100%', { fromValue: '61.32%'}], position: 40500, duration: 500 },
            { id: "eid543", tween: [ "style", "${_T-ARIAAOI}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid526", tween: [ "style", "${_T-ARIAAOI}", "display", 'block', { fromValue: 'none'}], position: 37500, duration: 0 },
            { id: "eid538", tween: [ "style", "${_T-ARIAAOI}", "display", 'none', { fromValue: 'block'}], position: 39500, duration: 0 },
            { id: "eid425", tween: [ "style", "${_T-slb1}", "left", '66.76%', { fromValue: '100%'}], position: 31500, duration: 500 },
            { id: "eid431", tween: [ "style", "${_T-slb1}", "left", '64.93%', { fromValue: '66.76%'}], position: 32000, duration: 1000 },
            { id: "eid435", tween: [ "style", "${_T-slb1}", "left", '100%', { fromValue: '64.93%'}], position: 33000, duration: 500 },
            { id: "eid114", tween: [ "style", "${_TXT-Title2}", "opacity", '1', { fromValue: '0'}], position: 12500, duration: 1000 },
            { id: "eid530", tween: [ "style", "${_U-ARIAAOI}", "left", '0%', { fromValue: '100%'}], position: 37500, duration: 500 },
            { id: "eid534", tween: [ "style", "${_U-ARIAAOI}", "left", '-2.21%', { fromValue: '0%'}], position: 38000, duration: 1000 },
            { id: "eid541", tween: [ "style", "${_U-ARIAAOI}", "left", '-41.03%', { fromValue: '-2.21%'}], position: 39000, duration: 500 },
            { id: "eid241", tween: [ "style", "${_U-WuYue}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid214", tween: [ "style", "${_U-WuYue}", "display", 'block', { fromValue: 'none'}], position: 20500, duration: 0 },
            { id: "eid232", tween: [ "style", "${_U-WuYue}", "display", 'none', { fromValue: 'block'}], position: 22500, duration: 0 },
            { id: "eid96", tween: [ "style", "${_gp13-6}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid88", tween: [ "style", "${_gp13-6}", "display", 'block', { fromValue: 'none'}], position: 6000, duration: 0 },
            { id: "eid90", tween: [ "style", "${_gp13-6}", "display", 'none', { fromValue: 'block'}], position: 10000, duration: 0 },
            { id: "eid158", tween: [ "style", "${_T-XiaoQiu}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid140", tween: [ "style", "${_T-XiaoQiu}", "display", 'block', { fromValue: 'none'}], position: 17500, duration: 0 },
            { id: "eid202", tween: [ "style", "${_T-XiaoQiu}", "display", 'none', { fromValue: 'block'}], position: 19500, duration: 0 },
            { id: "eid67", tween: [ "style", "${_gp13-4}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid53", tween: [ "style", "${_gp13-4}", "display", 'block', { fromValue: 'none'}], position: 2000, duration: 0 },
            { id: "eid61", tween: [ "style", "${_gp13-4}", "display", 'none', { fromValue: 'block'}], position: 6000, duration: 0 },
            { id: "eid309", tween: [ "style", "${_T-TonyZhao}", "top", '54.03%', { fromValue: '-14.84%'}], position: 25000, duration: 500 },
            { id: "eid313", tween: [ "style", "${_T-TonyZhao}", "top", '65.49%', { fromValue: '54.03%'}], position: 25500, duration: 1250 },
            { id: "eid319", tween: [ "style", "${_T-TonyZhao}", "top", '100%', { fromValue: '65.49%'}], position: 26750, duration: 500 },
            { id: "eid399", tween: [ "style", "${_U-KeKai}", "top", '9.63%', { fromValue: '100%'}], position: 30000, duration: 500 },
            { id: "eid408", tween: [ "style", "${_U-KeKai}", "top", '4.82%', { fromValue: '9.63%'}], position: 30500, duration: 1000 },
            { id: "eid416", tween: [ "style", "${_U-KeKai}", "top", '100%', { fromValue: '4.82%'}], position: 31500, duration: 500 },
            { id: "eid46", tween: [ "style", "${_gp13-3}", "display", 'none', { fromValue: 'block'}], position: 4000, duration: 0 },
            { id: "eid507", tween: [ "style", "${_U-MountainChen}", "left", '-3.38%', { fromValue: '-54.56%'}], position: 36000, duration: 500 },
            { id: "eid511", tween: [ "style", "${_U-MountainChen}", "left", '0%', { fromValue: '-3.38%'}], position: 36500, duration: 1000 },
            { id: "eid517", tween: [ "style", "${_U-MountainChen}", "left", '-54.56%', { fromValue: '0%'}], position: 37500, duration: 500 },
            { id: "eid391", tween: [ "style", "${_T-YookkeiLau}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid358", tween: [ "style", "${_T-YookkeiLau}", "display", 'block', { fromValue: 'none'}], position: 28500, duration: 0 },
            { id: "eid385", tween: [ "style", "${_T-YookkeiLau}", "display", 'none', { fromValue: 'block'}], position: 30500, duration: 0 },
            { id: "eid440", tween: [ "style", "${_T-slb1}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid422", tween: [ "style", "${_T-slb1}", "display", 'block', { fromValue: 'none'}], position: 31500, duration: 0 },
            { id: "eid438", tween: [ "style", "${_T-slb1}", "display", 'none', { fromValue: 'block'}], position: 33500, duration: 0 },
            { id: "eid542", tween: [ "style", "${_U-ARIAAOI}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid524", tween: [ "style", "${_U-ARIAAOI}", "display", 'block', { fromValue: 'none'}], position: 37500, duration: 0 },
            { id: "eid536", tween: [ "style", "${_U-ARIAAOI}", "display", 'none', { fromValue: 'block'}], position: 39500, duration: 0 },
            { id: "eid206", tween: [ "style", "${_T-jyuntang}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid175", tween: [ "style", "${_T-jyuntang}", "display", 'block', { fromValue: 'none'}], position: 19000, duration: 0 },
            { id: "eid204", tween: [ "style", "${_T-jyuntang}", "display", 'none', { fromValue: 'block'}], position: 21000, duration: 0 },
            { id: "eid508", tween: [ "style", "${_T-MountainChen}", "left", '65.59%', { fromValue: '100%'}], position: 36000, duration: 500 },
            { id: "eid512", tween: [ "style", "${_T-MountainChen}", "left", '63.24%', { fromValue: '65.59%'}], position: 36500, duration: 1000 },
            { id: "eid518", tween: [ "style", "${_T-MountainChen}", "left", '-30.73%', { fromValue: '63.24%'}], position: 37500, duration: 500 },
            { id: "eid240", tween: [ "style", "${_T-WuYue}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid215", tween: [ "style", "${_T-WuYue}", "display", 'block', { fromValue: 'none'}], position: 20500, duration: 0 },
            { id: "eid234", tween: [ "style", "${_T-WuYue}", "display", 'none', { fromValue: 'block'}], position: 22500, duration: 0 },
            { id: "eid106", tween: [ "style", "${_TXT-Title1}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid105", tween: [ "style", "${_TXT-Title1}", "display", 'block', { fromValue: 'none'}], position: 10000, duration: 0 },
            { id: "eid126", tween: [ "style", "${_TXT-Title1}", "display", 'none', { fromValue: 'block'}], position: 17500, duration: 0 },
            { id: "eid185", tween: [ "style", "${_T-jyuntang}", "left", '62.79%', { fromValue: '2.94%'}], position: 19000, duration: 500 },
            { id: "eid195", tween: [ "style", "${_T-jyuntang}", "left", '66.91%', { fromValue: '62.79%'}], position: 19500, duration: 1000 },
            { id: "eid200", tween: [ "style", "${_T-jyuntang}", "left", '100%', { fromValue: '66.91%'}], position: 20500, duration: 500 },
            { id: "eid92", tween: [ "style", "${_gp13-6}", "left", '-69.12%', { fromValue: '100%'}], position: 6000, duration: 4000 },
            { id: "eid499", tween: [ "style", "${_U-fzs}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid466", tween: [ "style", "${_U-fzs}", "display", 'block', { fromValue: 'none'}], position: 34500, duration: 0 },
            { id: "eid497", tween: [ "style", "${_U-fzs}", "display", 'none', { fromValue: 'block'}], position: 36500, duration: 0 },
            { id: "eid418", tween: [ "style", "${_T-KeKai}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid394", tween: [ "style", "${_T-KeKai}", "display", 'block', { fromValue: 'none'}], position: 30000, duration: 0 },
            { id: "eid412", tween: [ "style", "${_T-KeKai}", "display", 'none', { fromValue: 'block'}], position: 32000, duration: 0 },
            { id: "eid268", tween: [ "style", "${_T-XuShu}", "display", 'none', { fromValue: 'none'}], position: 0, duration: 0 },
            { id: "eid249", tween: [ "style", "${_T-XuShu}", "display", 'block', { fromValue: 'none'}], position: 22000, duration: 0 },
            { id: "eid262", tween: [ "style", "${_T-XuShu}", "display", 'none', { fromValue: 'block'}], position: 24000, duration: 0 }         ]
      }
   }
}
};


Edge.registerCompositionDefn(compId, symbols, fonts, resources);

/**
 * Adobe Edge DOM Ready Event Handler
 */
$(window).ready(function() {
     Edge.launchComposition(compId);
});
})(jQuery, AdobeEdge, "EDGE-9612029");
